"""Async Python client for the WattWächter smart meter API."""

from .client import Wattwaechter
from .exceptions import (
    WattwaechterAuthenticationError,
    WattwaechterConnectionError,
    WattwaechterError,
    WattwaechterNoDataError,
    WattwaechterRateLimitError,
)
from .models import (
    AliveResponse,
    CaCertStatus,
    HighResEntry,
    HighResHistory,
    HighResSummary,
    InfoEntry,
    LedColor,
    LedInfo,
    LedMode,
    LedStatus,
    LowResEntry,
    LowResHistory,
    MeterData,
    MqttConfig,
    ObisValue,
    OtaCheckResponse,
    OtaData,
    RgbColor,
    SelfTestResult,
    Settings,
    SystemInfo,
    TokenGenerateResponse,
    WifiConfig,
    WifiNetwork,
    WifiScanResponse,
)

__all__ = [
    "Wattwaechter",
    # Exceptions
    "WattwaechterError",
    "WattwaechterConnectionError",
    "WattwaechterAuthenticationError",
    "WattwaechterNoDataError",
    "WattwaechterRateLimitError",
    # Models
    "AliveResponse",
    "CaCertStatus",
    "HighResEntry",
    "HighResHistory",
    "HighResSummary",
    "InfoEntry",
    "LedColor",
    "LedInfo",
    "LedMode",
    "LedStatus",
    "LowResEntry",
    "LowResHistory",
    "MeterData",
    "MqttConfig",
    "ObisValue",
    "OtaCheckResponse",
    "OtaData",
    "RgbColor",
    "SelfTestResult",
    "Settings",
    "SystemInfo",
    "TokenGenerateResponse",
    "WifiConfig",
    "WifiNetwork",
    "WifiScanResponse",
]
